<?xml version="1.0" encoding="utf-8"?><Database Name="GroupWork" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\v12.0;Initial Catalog=GroupWork;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="WcfService2.Properties.Settings" SettingsPropertyName="GroupWorkConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Order]" Member="Orders">
    <Type Name="Order">
      <Column Name="Order_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Order_Number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Order_Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Active" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="User_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Product_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_Order" Member="Product" ThisKey="Product_ID" OtherKey="Product_ID" Type="Product" IsForeignKey="true" />
      <Association Name="User_Order" Member="User" ThisKey="User_ID" OtherKey="User_ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="Product_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="P_Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="P_Category_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="P_Description" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Discount_Amount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Supplier_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Availablle" Member="Available" Storage="_Availablle" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Member="NumProd" Type="System.Int32" CanBeNull="false" />
      <Association Name="Product_Order" Member="Orders" ThisKey="Product_ID" OtherKey="Product_ID" Type="Order" />
      <Association Name="Product_Category_Product" Member="Product_Category" ThisKey="P_Category_ID" OtherKey="PC_ID" Type="Product_Category" IsForeignKey="true" />
      <Association Name="Supplier_Product" Member="Supplier" ThisKey="Supplier_ID" OtherKey="Supp_ID" Type="Supplier" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product_Category" Member="Product_Categories">
    <Type Name="Product_Category">
      <Column Name="PC_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PC_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Product_Category_Product" Member="Products" ThisKey="PC_ID" OtherKey="P_Category_ID" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Reports" Member="Reports">
    <Type Name="Report">
      <Column Name="Report_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Num_Registered_Users" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Num_Products_Available" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Num_Products_Bought" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Supplier" Member="Suppliers">
    <Type Name="Supplier">
      <Column Name="Supp_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Supp_Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Supp_Email" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Supp_Contacts" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Association Name="Supplier_Product" Member="Products" ThisKey="Supp_ID" OtherKey="Supplier_ID" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="User_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Phone_Number" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="User_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Member="Password" Type="System.String" CanBeNull="false" />
      <Association Name="User_Order" Member="Orders" ThisKey="User_ID" OtherKey="User_ID" Type="Order" />
    </Type>
  </Table>
</Database>