//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmers_Field.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/ServiceApplication")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int activeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string first_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string last_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phone_numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string provinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int user_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string user_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string zip_codeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int active {
            get {
                return this.activeField;
            }
            set {
                if ((this.activeField.Equals(value) != true)) {
                    this.activeField = value;
                    this.RaisePropertyChanged("active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string first_name {
            get {
                return this.first_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.first_nameField, value) != true)) {
                    this.first_nameField = value;
                    this.RaisePropertyChanged("first_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.last_nameField, value) != true)) {
                    this.last_nameField = value;
                    this.RaisePropertyChanged("last_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone_number {
            get {
                return this.phone_numberField;
            }
            set {
                if ((object.ReferenceEquals(this.phone_numberField, value) != true)) {
                    this.phone_numberField = value;
                    this.RaisePropertyChanged("phone_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string province {
            get {
                return this.provinceField;
            }
            set {
                if ((object.ReferenceEquals(this.provinceField, value) != true)) {
                    this.provinceField = value;
                    this.RaisePropertyChanged("province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int user_ID {
            get {
                return this.user_IDField;
            }
            set {
                if ((this.user_IDField.Equals(value) != true)) {
                    this.user_IDField = value;
                    this.RaisePropertyChanged("user_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user_type {
            get {
                return this.user_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.user_typeField, value) != true)) {
                    this.user_typeField = value;
                    this.RaisePropertyChanged("user_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string zip_code {
            get {
                return this.zip_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.zip_codeField, value) != true)) {
                    this.zip_codeField = value;
                    this.RaisePropertyChanged("zip_code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/ServiceApplication")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int product_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string product_categoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string product_descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string product_discountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string product_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> product_priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string product_supplierField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int product_ID {
            get {
                return this.product_IDField;
            }
            set {
                if ((this.product_IDField.Equals(value) != true)) {
                    this.product_IDField = value;
                    this.RaisePropertyChanged("product_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string product_category {
            get {
                return this.product_categoryField;
            }
            set {
                if ((object.ReferenceEquals(this.product_categoryField, value) != true)) {
                    this.product_categoryField = value;
                    this.RaisePropertyChanged("product_category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string product_description {
            get {
                return this.product_descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.product_descriptionField, value) != true)) {
                    this.product_descriptionField = value;
                    this.RaisePropertyChanged("product_description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string product_discount {
            get {
                return this.product_discountField;
            }
            set {
                if ((object.ReferenceEquals(this.product_discountField, value) != true)) {
                    this.product_discountField = value;
                    this.RaisePropertyChanged("product_discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string product_name {
            get {
                return this.product_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.product_nameField, value) != true)) {
                    this.product_nameField = value;
                    this.RaisePropertyChanged("product_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> product_price {
            get {
                return this.product_priceField;
            }
            set {
                if ((this.product_priceField.Equals(value) != true)) {
                    this.product_priceField = value;
                    this.RaisePropertyChanged("product_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string product_supplier {
            get {
                return this.product_supplierField;
            }
            set {
                if ((object.ReferenceEquals(this.product_supplierField, value) != true)) {
                    this.product_supplierField = value;
                    this.RaisePropertyChanged("product_supplier");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        bool Login(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        int Register(Farmers_Field.ServiceReference.User FFieldUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        System.Threading.Tasks.Task<int> RegisterAsync(Farmers_Field.ServiceReference.User FFieldUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Registered", ReplyAction="http://tempuri.org/IService1/RegisteredResponse")]
        bool Registered(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Registered", ReplyAction="http://tempuri.org/IService1/RegisteredResponse")]
        System.Threading.Tasks.Task<bool> RegisteredAsync(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsNewProduct", ReplyAction="http://tempuri.org/IService1/IsNewProductResponse")]
        bool IsNewProduct(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsNewProduct", ReplyAction="http://tempuri.org/IService1/IsNewProductResponse")]
        System.Threading.Tasks.Task<bool> IsNewProductAsync(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddNewProduct", ReplyAction="http://tempuri.org/IService1/AddNewProductResponse")]
        bool AddNewProduct(Farmers_Field.ServiceReference.Product Prod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddNewProduct", ReplyAction="http://tempuri.org/IService1/AddNewProductResponse")]
        System.Threading.Tasks.Task<bool> AddNewProductAsync(Farmers_Field.ServiceReference.Product Prod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCartItems", ReplyAction="http://tempuri.org/IService1/getCartItemsResponse")]
        Farmers_Field.ServiceReference.Product[] getCartItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCartItems", ReplyAction="http://tempuri.org/IService1/getCartItemsResponse")]
        System.Threading.Tasks.Task<Farmers_Field.ServiceReference.Product[]> getCartItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddToCart", ReplyAction="http://tempuri.org/IService1/AddToCartResponse")]
        void AddToCart(Farmers_Field.ServiceReference.Product Item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddToCart", ReplyAction="http://tempuri.org/IService1/AddToCartResponse")]
        System.Threading.Tasks.Task AddToCartAsync(Farmers_Field.ServiceReference.Product Item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveFromCart", ReplyAction="http://tempuri.org/IService1/RemoveFromCartResponse")]
        void RemoveFromCart(Farmers_Field.ServiceReference.Product Item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveFromCart", ReplyAction="http://tempuri.org/IService1/RemoveFromCartResponse")]
        System.Threading.Tasks.Task RemoveFromCartAsync(Farmers_Field.ServiceReference.Product Item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProduct", ReplyAction="http://tempuri.org/IService1/GetProductResponse")]
        Farmers_Field.ServiceReference.Product GetProduct(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProduct", ReplyAction="http://tempuri.org/IService1/GetProductResponse")]
        System.Threading.Tasks.Task<Farmers_Field.ServiceReference.Product> GetProductAsync(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditProduct", ReplyAction="http://tempuri.org/IService1/EditProductResponse")]
        bool EditProduct(Farmers_Field.ServiceReference.Product Aug, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditProduct", ReplyAction="http://tempuri.org/IService1/EditProductResponse")]
        System.Threading.Tasks.Task<bool> EditProductAsync(Farmers_Field.ServiceReference.Product Aug, int ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Farmers_Field.ServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Farmers_Field.ServiceReference.IService1>, Farmers_Field.ServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string Email, string Password) {
            return base.Channel.Login(Email, Password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string Email, string Password) {
            return base.Channel.LoginAsync(Email, Password);
        }
        
        public int Register(Farmers_Field.ServiceReference.User FFieldUser) {
            return base.Channel.Register(FFieldUser);
        }
        
        public System.Threading.Tasks.Task<int> RegisterAsync(Farmers_Field.ServiceReference.User FFieldUser) {
            return base.Channel.RegisterAsync(FFieldUser);
        }
        
        public bool Registered(string Email, string Password) {
            return base.Channel.Registered(Email, Password);
        }
        
        public System.Threading.Tasks.Task<bool> RegisteredAsync(string Email, string Password) {
            return base.Channel.RegisteredAsync(Email, Password);
        }
        
        public bool IsNewProduct(string ID) {
            return base.Channel.IsNewProduct(ID);
        }
        
        public System.Threading.Tasks.Task<bool> IsNewProductAsync(string ID) {
            return base.Channel.IsNewProductAsync(ID);
        }
        
        public bool AddNewProduct(Farmers_Field.ServiceReference.Product Prod) {
            return base.Channel.AddNewProduct(Prod);
        }
        
        public System.Threading.Tasks.Task<bool> AddNewProductAsync(Farmers_Field.ServiceReference.Product Prod) {
            return base.Channel.AddNewProductAsync(Prod);
        }
        
        public Farmers_Field.ServiceReference.Product[] getCartItems() {
            return base.Channel.getCartItems();
        }
        
        public System.Threading.Tasks.Task<Farmers_Field.ServiceReference.Product[]> getCartItemsAsync() {
            return base.Channel.getCartItemsAsync();
        }
        
        public void AddToCart(Farmers_Field.ServiceReference.Product Item) {
            base.Channel.AddToCart(Item);
        }
        
        public System.Threading.Tasks.Task AddToCartAsync(Farmers_Field.ServiceReference.Product Item) {
            return base.Channel.AddToCartAsync(Item);
        }
        
        public void RemoveFromCart(Farmers_Field.ServiceReference.Product Item) {
            base.Channel.RemoveFromCart(Item);
        }
        
        public System.Threading.Tasks.Task RemoveFromCartAsync(Farmers_Field.ServiceReference.Product Item) {
            return base.Channel.RemoveFromCartAsync(Item);
        }
        
        public Farmers_Field.ServiceReference.Product GetProduct(string ID) {
            return base.Channel.GetProduct(ID);
        }
        
        public System.Threading.Tasks.Task<Farmers_Field.ServiceReference.Product> GetProductAsync(string ID) {
            return base.Channel.GetProductAsync(ID);
        }
        
        public bool EditProduct(Farmers_Field.ServiceReference.Product Aug, int ID) {
            return base.Channel.EditProduct(Aug, ID);
        }
        
        public System.Threading.Tasks.Task<bool> EditProductAsync(Farmers_Field.ServiceReference.Product Aug, int ID) {
            return base.Channel.EditProductAsync(Aug, ID);
        }
    }
}
