<?xml version="1.0" encoding="utf-8"?><Database Name="Farm_database" Class="Link_to_databaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localdb)\v12.0;Initial Catalog=Farm_database;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Farm_databaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Order]" Member="Orders">
    <Type Name="Order">
      <Column Name="order_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="order_number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="product_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Supplier" Member="Suppliers">
    <Type Name="Supplier">
      <Column Name="supplier_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="supplier_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="supplier_email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="supplier_contact" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="supplier_country" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="product_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="product_category" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="product_name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="product_description" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="product_price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="product_discount" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="product_supplier" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="user_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="last_name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="phone_number" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="user_type" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="city" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="province" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="zip_code" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>